# Generated by Django 6.0.3 on 2026-03-31 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('competition', models.CharField(choices=[('UCL', 'UEFA Champions League')], default='UCL', max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('pot_count', models.PositiveSmallIntegerField(default=4)),
                ('teams_per_pot', models.PositiveSmallIntegerField(default=9)),
                ('total_matches', models.PositiveSmallIntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=30)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='draw.association')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeasonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uefa_club_coefficient', models.DecimalField(decimal_places=3, max_digits=7)),
                ('is_title_holder', models.BooleanField(default=False)),
                ('qualified_via', models.CharField(choices=[('TITLE_HOLDER', 'Title holder'), ('LEAGUE_POSITION', 'League position'), ('EUROPA_LEAGUE', 'Europa League title holder'), ('CHAMPIONS_PATH', 'Champions path'), ('LEAGUE_PATH', 'League path'), ('PERFORMANCE_SPOT', 'European performance spot'), ('OTHER', 'Other')], default='LEAGUE_POSITION', max_length=30)),
                ('seeding_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='draw.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_entries', to='draw.team')),
            ],
            options={
                'ordering': ['pot', 'seeding_position', 'team__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('association', 'name'), name='unique_team_name_per_association'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('association', 'short_name'), name='unique_team_short_name_per_association'),
        ),
        migrations.AddConstraint(
            model_name='seasonteam',
            constraint=models.UniqueConstraint(fields=('season', 'team'), name='unique_team_per_season'),
        ),
    ]
