# Generated by Django 6.0.3 on 2026-04-07 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonMatchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matchups', to='draw.seasonteam')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matchups', to='draw.seasonteam')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='draw.season')),
            ],
            options={
                'ordering': ['season__name', 'matchday', 'home_team__team__name', 'away_team__team__name'],
                'constraints': [models.UniqueConstraint(fields=('season', 'home_team', 'away_team'), name='unique_directed_matchup_per_season'), models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='prevent_self_matchup')],
            },
        ),
    ]
