# Generated by Django 6.0.3 on 2026-06-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_seasonmatchup'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team_short_name_per_association',
        ),
    ]
