# Generated by Django 6.0.3 on 2026-06-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0005_team_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasondraw',
            name='player_name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
