# Generated by Django 6.0.3 on 2026-08-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0007_prediction_playoffprediction_matchprediction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonmatchup',
            name='away_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonmatchup',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='seasonmatchup',
            name='home_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonmatchup',
            name='kickoff',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seasonmatchup',
            name='status',
            field=models.CharField(blank=True, default='', help_text='SCHEDULED, IN_PLAY, FINISHED, etc.', max_length=20),
        ),
    ]
