# Generated by Django 6.0.3 on 2026-08-26 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0008_seasonmatchup_away_goals_seasonmatchup_external_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='API code, e.g. PL, BL1, CL', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('emblem_url', models.URLField(blank=True, default='', max_length=500)),
                ('plan', models.CharField(blank=True, default='', help_text='API plan tier (TIER_ONE, etc.)', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeagueStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.PositiveSmallIntegerField()),
                ('position', models.PositiveSmallIntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('team_crest', models.URLField(blank=True, default='', max_length=500)),
                ('played', models.PositiveSmallIntegerField(default=0)),
                ('won', models.PositiveSmallIntegerField(default=0)),
                ('draw', models.PositiveSmallIntegerField(default=0)),
                ('lost', models.PositiveSmallIntegerField(default=0)),
                ('goals_for', models.PositiveSmallIntegerField(default=0)),
                ('goals_against', models.PositiveSmallIntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='draw.league')),
            ],
            options={
                'ordering': ['league', 'season_year', 'position'],
                'constraints': [models.UniqueConstraint(fields=('league', 'season_year', 'team_name'), name='unique_team_per_league_season')],
            },
        ),
    ]
