# Generated by Django 6.0.3 on 2026-08-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0009_league_leaguestanding'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonMatchupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_away_matchups', to='draw.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_home_matchups', to='draw.team')),
            ],
            options={
                'ordering': ['season_name'],
                'constraints': [models.UniqueConstraint(fields=('season_name', 'home_team', 'away_team'), name='unique_directed_history_per_season')],
            },
        ),
    ]
