# Generated by Django 6.0.3 on 2026-08-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0010_seasonmatchuphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasondraw',
            name='method',
            field=models.CharField(choices=[('sat', 'SAT (uniform draws)'), ('sequential', 'Sequential (UEFA-style)')], default='sat', help_text='Draw generation algorithm: sat (uniform) or sequential (UEFA-style).', max_length=20),
        ),
    ]
