# Generated by Django 6.0.3 on 2026-08-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0011_seasondraw_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveDrawPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_order', models.PositiveSmallIntegerField()),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='draw.seasondraw')),
                ('season_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_picks', to='draw.seasonteam')),
            ],
            options={
                'ordering': ['pick_order'],
                'constraints': [
                    models.UniqueConstraint(fields=['draw', 'season_team'], name='unique_interactive_pick_team_per_draw'),
                ],
            },
        ),
    ]