# Generated by Django 6.0.3 on 2026-08-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0012_interactivedrawpick'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasondraw',
            name='interactive_edges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='seasondraw',
            name='method',
            field=models.CharField(choices=[('sat', 'SAT (uniform draws)'), ('sequential', 'Sequential (UEFA-style)'), ('interactive', 'Interactive (manual ceremony)')], default='sat', help_text='Draw generation algorithm: sat (uniform) or sequential (UEFA-style).', max_length=20),
        ),
    ]
