# Generated by Django 6.0.3 on 2026-09-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0013_seasondraw_interactive_edges_alter_seasondraw_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonteam',
            name='domestic_position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
