# Generated by Django 6.0.3 on 2026-09-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0014_seasonteam_domestic_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='knockoutprediction',
            name='et_away_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knockoutprediction',
            name='et_home_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knockoutprediction',
            name='pen_away_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knockoutprediction',
            name='pen_home_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playoffprediction',
            name='et_away_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playoffprediction',
            name='et_home_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playoffprediction',
            name='extra_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playoffprediction',
            name='pen_away_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playoffprediction',
            name='pen_home_goals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playoffprediction',
            name='penalties',
            field=models.BooleanField(default=False),
        ),
    ]
