# Generated by Django 6.0.3 on 2026-09-08 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0015_knockoutprediction_et_away_goals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealFixturePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.PositiveSmallIntegerField()),
                ('home_goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_real_preds', to='draw.seasonteam')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_real_preds', to='draw.seasonteam')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_fixture_predictions', to='draw.prediction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('prediction', 'home_team', 'away_team'), name='unique_real_prediction')],
            },
        ),
    ]
