# Generated by Django 6.0.3 on 2026-09-08 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0016_realfixtureprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.BigIntegerField(help_text='football-data.org fixture id', unique=True)),
                ('home_name', models.CharField(max_length=100)),
                ('away_name', models.CharField(max_length=100)),
                ('home_short', models.CharField(blank=True, default='', max_length=60)),
                ('away_short', models.CharField(blank=True, default='', max_length=60)),
                ('home_crest', models.URLField(blank=True, default='', max_length=500)),
                ('away_crest', models.URLField(blank=True, default='', max_length=500)),
                ('kickoff', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='SCHEDULED', max_length=20)),
                ('matchday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('home_goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='draw.league')),
            ],
            options={
                'ordering': ['kickoff'],
            },
        ),
    ]
