# Generated by Django 6.0.3 on 2026-09-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0017_leaguematch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='competition',
            field=models.CharField(choices=[('UCL', 'UEFA Champions League'), ('LIB', 'Copa Libertadores'), ('SUD', 'Copa Sudamericana')], default='UCL', max_length=10),
        ),
    ]
