# Generated by Django 6.0.3 on 2026-09-20 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0018_add_conmebol_competition_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueMatchPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=80)),
                ('home_goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_goals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='draw.leaguematch')),
            ],
            options={
                'ordering': ['match', 'player_name'],
                'constraints': [models.UniqueConstraint(fields=('match', 'player_name'), name='unique_league_prediction_per_player')],
            },
        ),
    ]
