# Generated by Django 6.0.3 on 2026-09-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0019_leaguematchprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealFixtureResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_id', models.CharField(max_length=50, unique=True)),
                ('home_goals', models.PositiveSmallIntegerField()),
                ('away_goals', models.PositiveSmallIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fixture_id'],
            },
        ),
    ]
