# Generated by Django 6.0.3 on 2026-09-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0021_friendlies_competition_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='competition',
            field=models.CharField(choices=[('UCL', 'UEFA Champions League'), ('LIB', 'Copa Libertadores'), ('SUD', 'Copa Sudamericana'), ('FRN', 'International Friendlies'), ('UNL', 'UEFA Nations League')], default='UCL', max_length=10),
        ),
        migrations.CreateModel(
            name='ResultHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('competition', models.CharField(max_length=10)),
                ('season_name', models.CharField(blank=True, default='', max_length=20)),
                ('subject', models.CharField(max_length=80)),
                ('home_label', models.CharField(max_length=100)),
                ('away_label', models.CharField(max_length=100)),
                ('home_goals', models.PositiveSmallIntegerField(null=True)),
                ('away_goals', models.PositiveSmallIntegerField(null=True)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-observed_at', '-id'],
                'indexes': [models.Index(fields=['source', 'subject'], name='rh_source_subject_idx')],
            },
        ),
    ]
