# Generated by Django 6.0.3 on 2026-09-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0022_resulthistory_nations_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='promiedos_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
