# Generated by Django 6.0.3 on 2026-09-24 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0023_team_promiedos_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=160)),
                ('founded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('club_city', models.CharField(blank=True, default='', max_length=160)),
                ('stadium_name', models.CharField(blank=True, default='', max_length=200)),
                ('stadium_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('stadium_city', models.CharField(blank=True, default='', max_length=160)),
                ('primary_color', models.CharField(blank=True, default='', max_length=9)),
                ('text_color', models.CharField(blank=True, default='', max_length=9)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='draw.team')),
            ],
            options={
                'ordering': ['team__name'],
            },
        ),
        migrations.CreateModel(
            name='SquadPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('shirt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_date', models.CharField(blank=True, default='', max_length=20)),
                ('height', models.CharField(blank=True, default='', max_length=10)),
                ('group', models.CharField(blank=True, default='', max_length=40)),
                ('promiedos_player_id', models.CharField(blank=True, default='', max_length=32)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad', to='draw.team')),
            ],
            options={
                'ordering': ['team__name', 'group', 'name'],
                'constraints': [models.UniqueConstraint(fields=('team', 'name'), name='unique_squad_player_per_team')],
            },
        ),
        migrations.CreateModel(
            name='TeamStatLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(max_length=160)),
                ('metric', models.CharField(max_length=80)),
                ('player_name', models.CharField(max_length=120)),
                ('player_short_name', models.CharField(blank=True, default='', max_length=80)),
                ('rank', models.PositiveSmallIntegerField()),
                ('value', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_leaders', to='draw.team')),
            ],
            options={
                'ordering': ['team__name', 'competition', 'metric', 'rank'],
                'constraints': [models.UniqueConstraint(fields=('team', 'competition', 'metric', 'player_name'), name='unique_stat_leader_per_team')],
            },
        ),
    ]
